name: CI Pipeline

on:
  push:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 mypy bandit pip-audit

      # -------- TIPADO --------
      - name: Type check (mypy)
        run: mypy src tests apps

      # -------- LINT --------
      - name: Lint (flake8)
        run: flake8 src tests apps

      # -------- SEGURIDAD: BANDIT --------
      # Falla con cualquier hallazgo (low/medium/high con cualquier nivel de confianza)
      - name: Security scan (Bandit)
        run: |
          bandit -r src/ apps/ --severity-level low --confidence-level low -f txt -o bandit-report.txt
          cat bandit-report.txt

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.txt

      # -------- SEGURIDAD: DEPENDENCIAS --------
      - name: Dependency audit (pip-audit)
        run: pip-audit

      # -------- TESTS + COVERAGE --------
      - name: Tests + coverage
        run: |
          pytest --maxfail=1 -ra \
                 --cov=src \
                 --cov-report=term-missing \
                 --cov-report=xml \
                 --cov-fail-under=80

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: HTML coverage (artifact)
        if: always()
        run: pytest --cov=src --cov-report=html

      - name: Upload htmlcov
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov